import { Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import Header from "@/components/Header";
import Sidebar from "@/components/Sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={cn(inter.className, 'bg-white')}>
        <div className="flex flex-col lg:flex-row min-h-screen">
          <div className="hidden lg:block lg:w-1/4">
            <Sidebar />
          </div>
          <div className="flex flex-col flex-grow lg:w-3/4">
            <Header />
            <main className="flex-grow p-8">
              {children}
            </main>
          </div>
        </div>
      </body>
    </html>
  );
}
