import { Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import Sidebar from "@/components/Sidebar";
import Header from "@/components/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={cn(inter.className, 'bg-white')}>
        <section>
          <Header />
        </section>

        <div className="flex flex-row">
          <div className="py-4 px-2 ml-8 mr-16">
            <Sidebar />
          </div>
          <main className="px-8 py-8">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
